name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every day at midnight UTC
    - cron: '30 18 * * *'
    # Run every day at 12:30 PM IST (07:00 UTC)
    - cron: '0 7 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests
        run: mvn clean test

      - name: Generate Maven Surefire Report
        run: mvn surefire-report:report

      - name: Upload TestNG HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-html-report
          path: target/surefire-reports/

      - name: Upload Screenshots
        if: always() # ensures it runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: screenshots/
          if-no-files-found: ignore

      - name: List screenshot files
        if: always()
        run: ls -R screenshots || echo "No screenshots found"

      - name: Send test report via email
        if: always()  # ensures it runs even if tests fail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Selenium Test Report - ${{ github.run_number }}"
          to: ${{ secrets.MAIL_TO }}
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          body: |
            Hello Tester,

            The latest Selenium test run has completed.
            Repository: ${{ github.repository }}
            Run Number: ${{ github.run_number }}
            Triggered by: ${{ github.actor }}

            Please find the attached report.

            Thanks,
            GitHub Actions
          attachments: |
            target/surefire-reports/index.html

